### PR TITLE
feat(distribution): rename product to bici

### PR DESCRIPTION
**Pull request by laurentleseigneur**
Relates to [ICI-1012](https://bonitasoft.atlassian.net/browse/ICI-1012)

### CODE REVIEW

**Comment by laurentleseigneur** [comment]
retest this please

**Comment by laurentleseigneur** [comment]
retest this please

**Comment by laurentleseigneur** [comment]
retest this please

**Comment by laurentleseigneur** [comment]
retest this please

**Comment by tnguyen1** [comment]
retest this please

**Pull request merged**
